---
resources:
  - name: explore-oci-build-task
    type: git
    source:
      uri: https://github.com/crhntr/explore-oci-build-task

jobs:
  - name: build
    plan:
      - get: explore-oci-build-task
        trigger: true
      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          inputs:
            - name: explore-oci-build-task
              path: .
          outputs:
            - name: image
          env:
            UNPACK_ROOTFS: true
          run:
            path: build
      - task: "run"
        image: image
        config:
          platform: linux
          inputs:
            - name: explore-oci-build-task
          run:
            path: go
            args: ["run", "."]

