---
resources:
  - name: &repo-name explore-oci-build-task
    type: git
    source:
      uri: https://github.com/crhntr/explore-oci-build-task

jobs:
  - name: build
    plan:
      - get: *repo-name
        trigger: true
      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          inputs:
            - name: *repo-name
              path: .
          outputs:
            - name: image
          params:
            UNPACK_ROOTFS: true
          run:
            path: build
      - task: "run"
        image: image
        config:
          platform: linux
          inputs:
            - name: explore-oci-build-task
          params:
            SOME_VARIABLE: "¡Hola, mundo!"
          run:
            path: "/main"

