---
resources:
  - name: explore-oci-build-task
    type: git
    source:
      uri: https://github.com/crhntr/explore-oci-build-task

jobs:
  - name: build
    plan:
      - get: explore-oci-build-task
        trigger: true
      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          inputs:
            - name: explore-oci-build-task
              path: .
          outputs:
            - name: image
          params:
            UNPACK_ROOTFS: true
          run:
            path: build
      - task: "smoke-test"
        image: image
        config:
          platform: linux
          inputs:
            - name: explore-oci-build-task
          params:
            GREETING: "Hello, Build!"
          run:
            path: "/main"

  - name: spanish
    plan:
      - task: "greet"
        image: image
        config:
          platform: linux
          inputs:
            - name: explore-oci-build-task
          params:
            GREETING: "¡Hola, mundo!"
          run:
            path: "/main"

  - name: english
    plan:
      - task: "greet"
        image: image
        config:
          platform: linux
          inputs:
            - name: explore-oci-build-task
          params:
            GREETING: "Hello, World!"
          run:
            path: "/main"
